package repositories

import (
	"database/sql"

	"backend-sarpras/models"
)

type MailboxRepository struct {
	DB *sql.DB
}

func NewMailboxRepository(db *sql.DB) *MailboxRepository {
	return &MailboxRepository{DB: db}
}

// Create inserts a new mailbox record (kode_mailbox auto-generated by trigger)
func (r *MailboxRepository) Create(mailbox *models.Mailbox) error {
	query := `
		INSERT INTO mailbox (kode_user, kode_peminjaman, jenis_pesan)
		VALUES ($1, $2, $3)
		RETURNING kode_mailbox, created_at`

	return r.DB.QueryRow(query,
		mailbox.KodeUser,
		mailbox.KodePeminjaman,
		mailbox.JenisPesan,
	).Scan(&mailbox.KodeMailbox, &mailbox.CreatedAt)
}

// GetByID retrieves a mailbox record by kode_mailbox
func (r *MailboxRepository) GetByID(kodeMailbox string) (*models.Mailbox, error) {
	query := `
		SELECT kode_mailbox, kode_user, kode_peminjaman, jenis_pesan, created_at
		FROM mailbox
		WHERE kode_mailbox = $1`

	mailbox := &models.Mailbox{}
	err := r.DB.QueryRow(query, kodeMailbox).Scan(
		&mailbox.KodeMailbox,
		&mailbox.KodeUser,
		&mailbox.KodePeminjaman,
		&mailbox.JenisPesan,
		&mailbox.CreatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return mailbox, nil
}

// GetFullDataByID retrieves mailbox with all joined data for email template
func (r *MailboxRepository) GetFullDataByID(kodeMailbox string) (*models.MailboxWithDetails, error) {
	query := `
		SELECT 
			m.kode_mailbox,
			m.jenis_pesan,
			m.created_at,
			
			-- Penerima
			u_penerima.email AS email_tujuan,
			
			-- Peminjaman
			p.kode_peminjaman,
			COALESCE(p.status::text, '') AS status,
			COALESCE(p.catatan_verifikasi, '') AS catatan_verifikasi,
			p.tanggal_mulai,
			p.tanggal_selesai,
			
			-- Peminjam
			COALESCE(u_peminjam.nama, '') AS nama_peminjam,
			COALESCE(u_peminjam.email, '') AS email_peminjam,
			COALESCE(u_peminjam.no_hp, '') AS no_hp_peminjam,
			
			-- Organisasi
			COALESCE(o.nama, '') AS nama_organisasi,
			
			-- Ruangan
			COALESCE(r.nama_ruangan, '') AS nama_ruangan,
			COALESCE(r.lokasi, '') AS lokasi_ruangan,
			COALESCE(r.kapasitas, 0) AS kapasitas,
			
			-- Kegiatan
			COALESCE(k.nama_kegiatan, '') AS nama_kegiatan,
			COALESCE(k.deskripsi, '') AS deskripsi_kegiatan,
			
			-- Verifikator
			COALESCE(u_verif.nama, '') AS nama_verifikator

		FROM mailbox m
		JOIN users u_penerima ON m.kode_user = u_penerima.kode_user
		JOIN peminjaman p ON m.kode_peminjaman = p.kode_peminjaman
		JOIN users u_peminjam ON p.kode_user = u_peminjam.kode_user
		LEFT JOIN organisasi o ON u_peminjam.organisasi_kode = o.kode_organisasi
		LEFT JOIN ruangan r ON p.kode_ruangan = r.kode_ruangan
		LEFT JOIN kegiatan k ON p.kode_kegiatan = k.kode_kegiatan
		LEFT JOIN users u_verif ON p.verified_by = u_verif.kode_user
		WHERE m.kode_mailbox = $1`

	data := &models.MailboxWithDetails{}
	err := r.DB.QueryRow(query, kodeMailbox).Scan(
		&data.KodeMailbox,
		&data.JenisPesan,
		&data.CreatedAt,
		&data.EmailTujuan,
		&data.KodePeminjaman,
		&data.Status,
		&data.CatatanVerifikasi,
		&data.TanggalMulai,
		&data.TanggalSelesai,
		&data.NamaPeminjam,
		&data.EmailPeminjam,
		&data.NoHPPeminjam,
		&data.NamaOrganisasi,
		&data.NamaRuangan,
		&data.LokasiRuangan,
		&data.Kapasitas,
		&data.NamaKegiatan,
		&data.DeskripsiKegiatan,
		&data.NamaVerifikator,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return data, nil
}

// GetByUser retrieves all mailbox records for a user
func (r *MailboxRepository) GetByUser(kodeUser string) ([]models.Mailbox, error) {
	query := `
		SELECT kode_mailbox, kode_user, kode_peminjaman, jenis_pesan, created_at
		FROM mailbox
		WHERE kode_user = $1
		ORDER BY created_at DESC`

	rows, err := r.DB.Query(query, kodeUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var mailboxes []models.Mailbox
	for rows.Next() {
		var m models.Mailbox
		if err := rows.Scan(
			&m.KodeMailbox,
			&m.KodeUser,
			&m.KodePeminjaman,
			&m.JenisPesan,
			&m.CreatedAt,
		); err != nil {
			return nil, err
		}
		mailboxes = append(mailboxes, m)
	}
	return mailboxes, nil
}

// GetByPeminjaman retrieves all mailbox records for a peminjaman
func (r *MailboxRepository) GetByPeminjaman(kodePeminjaman string) ([]models.Mailbox, error) {
	query := `
		SELECT kode_mailbox, kode_user, kode_peminjaman, jenis_pesan, created_at
		FROM mailbox
		WHERE kode_peminjaman = $1
		ORDER BY created_at DESC`

	rows, err := r.DB.Query(query, kodePeminjaman)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var mailboxes []models.Mailbox
	for rows.Next() {
		var m models.Mailbox
		if err := rows.Scan(
			&m.KodeMailbox,
			&m.KodeUser,
			&m.KodePeminjaman,
			&m.JenisPesan,
			&m.CreatedAt,
		); err != nil {
			return nil, err
		}
		mailboxes = append(mailboxes, m)
	}
	return mailboxes, nil
}
